seed_everything: 7
trainer:
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 1
        monitor: val_acc
        mode: max
        filename: '{epoch}-{step}-{val_acc:.6f}'
  accelerator: cpu
  devices: 1
  check_val_every_n_epoch: 2 # 5
  max_epochs: 50
  deterministic: true

wandb:
  name: "test1"
  project: "ImageForgeryDetection"
  log_model: "all"


model:
  num_classes: 2
  d_model: 256

  #spatial transformer
  requires_grad: false
  drop_rate: 0.1
  proj_drop_rate: 0.1
  attn_drop_rate: 0.1
  drop_path_rate: 0.1

  growth_rate: 16
  num_layers: 12

  # training
  learning_rate: 0.0001
  weight_decay: 0.0
  patience: 8

data:
  folder_path: "data/CASIA1"
  num_workers: 4
  train_batch_size: 32
  val_batch_size: 16
